[meta]
  host_url = "https://{{.username}}:{{.password}}@dynupdate.no-ip.com"
  method   = "GET"
  response = "good|nochg"

[ipv4]
  path = "/nic/update?hostname={{.hostname}}&myip={{.ipv4}}"
  body = ""

[ipv6]
  path = "/nic/update?hostname={{.hostname}}&myip={{.ipv6}}"
  body = ""

[args]
  hostname = "test.ddns.net"
  username = "user"
  password = "pass"
